Implemented the remove (bulk delete from user) command
unixporn/trup pull request #10
Opened 2020-05-18 20:45 UTC by aosync

Implemented the remove command as described in #3  

`.remove <amount> <@user>` deletes the `amount` amount of messages from the user.
Because discord has a fetching messages limit of 100, and that we are targetting a particular user, I chose to iterate several number of times (up to 10 times) through the ranges [100n-100; 100n] of previous messages until it gets through the required amount of messages. If after 10 iterations, the bot cannot find the required amount of messages, it will just give up and delete the ones it has yet found.

The iterations also stop once it gets to a message that's older than 14 days since bulk delete do not work for such old messages.

2020-05-19 05:13 UTC, aosync commented
Don't merge yet, once I can, I will commit the use of a label instead of that messy `breakFromOuter`.

2020-05-19 13:45 UTC, aosync commented
Ok I think I am done. Tell me if there are still things to do.

2020-05-19 16:35 UTC, mlvzk requested changes

2020-05-19 16:35 UTC, mlvzk commented on command/command.go
> +		Help: removeUsage,
```suggestion
		Usage: removeUsage,
```

2020-05-20 20:48 UTC, merged

2020-05-20 20:48 UTC, mlvzk commented
Merged, thank you.